name: "Deploy WordPress to WP Engine"
branding:
  icon: "upload-cloud"
  color: "blue"
description: "Deploy WordPress projects to a WP Engine account using SSH Gateway"
inputs:
  WPE_SSHG_KEY_PRIVATE:
    description: "The private RSA key you will save in the Github Secrets"
    required: true
  PHP_LINT:
    description: "optional php syntax check"
    required: false
  FLAGS: 
    description: "optional flags for the deployment"
    required: true
    default: '-azvr --inplace --exclude=".*"'
  TPO_SRC_PATH:
    description: "An optional source directory to deploy other than the root directory that is being versioned."
    default: ""
    required: false
  TPO_PATH:
    description: "An optional destination directory to deploy to other than the WordPress root."
    default: ""
    required: false
  PRD_BRANCH: 
    description: "Source branch to deploy PRD_ENV"
    required: true
  PRD_ENV:
    description: "Destination to deploy to WPE Prod"
    required: false
  STG_BRANCH: 
    description: "Source branch to deploy STG_ENV"
    required: false
  STG_ENV:
    description: "Destination to deploy to WPE Stage"
    required: false
  DEV_BRANCH: 
    description: "Source branch to deploy DEV_ENV"
    required: false
  DEV_ENV:
    description: "Destination to deploy to WPE Dev"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"